---
title: 'introduction'
teaching: 10
exercises: 2
---

The course is written in 2 parts and serves to complement longer training courses written by members of ELIXIR-CONVERGE.  The first part of this course provides concise, didactic FAIR background and signposting to useful resources and literature.  From this section learners will be able to familiarise themselves with basic content and follow links to additional reading and training resources, if they wish to pursue a concept in more depth.  The aim here is to give enough overview required for the second part of this course where real data examples are used to demonstrate FAIR in practice and engage in active learning.

**This work is funded by a UKRI Innovation Scholars award (MR/C038966/1).**


## You will learn about:

1- The FAIR Principles and related terms such as FAIRification and FAIRness of data.
2- The difference between FAIR and Open data.
3- The origins of FAIR.
4- Why FAIR is important.
5- How data is made FAIR through showing worked examples.


## Prerequisites

This is a basic course and no prior knowledge is necessary.
