---
title: 'Metadata'
teaching: 10
exercises: 2
---
::: callout
## Objectives
1- To identify what are metadata and its types

3- To take part in understanding what are the community standards and how to use them for data and metadata

4- To define what is data provenance

5- To illustrate what is rich metadata and how to use them

6- To explain how to explicitly use rich metadata to describe your data
:::

## Meta-data



::: callout
## Resources

- [Introduction to metadata](https://carpentries-incubator.github.io/fair-bio-practice/05-intro-to-metadata/index.html)
- [Data in Excel](https://carpentries-incubator.github.io/fair-bio-practice/07-data-in-excel/index.html)
- [Metadata profiles](https://faircookbook.elixir-europe.org/content/recipes/interoperability/creating-minimal-metadata-profiles.html)
- [Metadata management](https://rdmkit.elixir-europe.org/metadata_management.html)
:::

::::::::::: challenge
- From the following resources, Can you determine what are the types of metadata in this dataset [E-MTAB-7933](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-7933)?
::::::::::::::::


<p style="text-align: center;"> Metadata and data are always available </p>

**(A2)** Metadata are accessible, even when the data are no longer available

:::::::::::::: challenge
- From the previous resources: would you give an example of metadata without data?
:::::::::::::::::

<p style="text-align: center;"> Data and metadata should follow Community standards </p>

::: callout
## Resources
- RDMkit resources on [community standards](https://rdmkit.elixir-europe.org/your_domain), you will find resources for different research fields
- [Domain specific repositories](https://carpentries-incubator.github.io/fair-bio-practice/13-data-repositories/index.html)
- [How do we choose a research data repository?](https://carpentries-incubator.github.io/fair-bio-practice/13-data-repositories/index.html)
:::

::: challenge
## Exercise
Based on the previous resources, Could you know what will be the appropriate repository suitable for bioimaging data?
:::

<p style="text-align: center;"> Provenance </p>

::: callout
- [How can you record data provenance](https://rdmkit.elixir-europe.org/data_provenance)
- [Audit of the provenence process](https://faircookbook.elixir-europe.org/content/recipes/reusability/provenance.html)
- [metadata vocabularies](https://lov.linkeddata.es/dataset/lov/)
::: 

<p style="text-align: center;"> Vocabularies are FAIR </p>
(I2)  (meta)data use vocabularies that follow FAIR principles
(I1)  (meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation


::: callout
- [FAIR and the notion of metadata](https://faircookbook.elixir-europe.org/content/recipes/introduction/metadata-fair.html)
- [Machine readability](https://rdmkit.elixir-europe.org/machine_actionability)
- [Vocabularies and ontology](https://carpentries-incubator.github.io/fair-bio-practice/06-being-precise/index.html)
- [List of ontology](https://obofoundry.org/)
:::

<p style="text-align: center;"> Linked metadata </p>
(I3)  (meta)data include qualified references to other (meta)data

::: callout
- [Interlinking data from different sources](https://faircookbook.elixir-europe.org/content/recipes/interoperability/identifier-mapping.html#references)
:::

::::::::::: challenge
- From the previous resources, Can you extract data provenance from this data set [E-MTAB-7933](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-7933)? 
- Define what is ontology?
::::::::::::::::
