---
title: "Access"
teaching: 10
exercises: 2
---

::: callout
## Objectives
Objectives:
1- To illustrate what is the communications protocol     
2- To articulate  what are the criteria for open and free protocol
3- To relate to the quote “As open as possible as close as necessary” by giving examples on sensitive data
3- To give examples of  databases that uses a protocol with   different  authentication process 
4- To interpret the usage licence associated with different data sets

:::


### Standard communication protocol


(A1)   	(meta)data are retrievable by their identifier using a standardised communications protocol


::: callout
## Resources
- [SSH protocols](https://faircookbook.elixir-europe.org/content/recipes/accessibility/sftp.html)
- [Protocols and safety of data transfer](https://rdmkit.elixir-europe.org/data_transfer.html)
:::

::: challenge
## Exercise
After reading this guide on different [protocol types](https://rdmkit.elixir-europe.org/data_transfer.html#how-do-you-transfer-large-data-files), give an example on one of databases that uses one of these protocols?
:::

### Data usage licence


(R1.1)	meta(data) are released with a clear and accessible data usage licence


::: callout
- Why should you assign licence to your protocol from [here](https://rdmkit.elixir-europe.org/licensing)
- Step by step process for [licence](https://faircookbook.elixir-europe.org/content/recipes/reusability/ATI-licensing.html)
- Step by step process for [software licence](https://faircookbook.elixir-europe.org/content/recipes/reusability/ATI_licensing_software.html)
- Step by step process for [Data licence](https://faircookbook.elixir-europe.org/content/recipes/reusability/ATI_licensing_data.html)
- Step by step process for [Declaring data permitted uses](https://faircookbook.elixir-europe.org/content/recipes/reusability/expressing-data-use.html)
- [Creative commons licence](https://creativecommons.org/choose/)
:::


:::
## Exercise
- From the previous resources that we provided, what is the licence used by the following databases:
1- Zenodo
2- arrayexpress
::: 

## Sensitive data

::: callout
## Resources
- [What is sensitive data?](https://rdmkit.elixir-europe.org/sensitive_data)
- [How to describe the permitted use of data](https://faircookbook.elixir-europe.org/content/recipes/reusability/expressing-data-use.html#)
- [ELSI and GDPR](https://scilifelab-data-guidelines.readthedocs.io/en/latest/docs/general/sensitive_data.html)
:::



