---
title: "Registration"
teaching: 10
exercises: 2
---

::: callout
## Objectives
1- To define what is data repository?

2- To illustrate different types of data repository

3- To summarize steps of data indexing in a searchable repository
:::

<p style="text-align: center;">Indexed data repository</p>

**(F4)** (meta)data are registered or indexed in a searchable resource

To ensure data findability, your data should be uploaded to a public repository where your data can be searched and found, which is why F4 is so vital. There are numerous databases where you can upload your data, these are typically data-driven. 
Examples of these databases are **Arrayexpress** for microarray data and RNAseq data. These databases have set of rules in place to make sure that your data will be FAIR.

After you upload your data into this database, they are assigned an ID and are indexed in the database. So whenever you look for the ID, or even use a keyword for your data, you will find your data.

::::::: challenge
You have a dataset and you want to upload it to Wikidata, Can you do this using one of FAIRcookbook recipes?
::::::::: solution
As we explained before the structure of the recipe so let's look for the suitable recipe in the FAIRcookbook

So as you can see the 


:::::::::::

As you can see in the following example how this dataset is indexed and can be searchable using the array express search box

Our resources provide an overview of data repositories and examples.


::: callout
## Resources
The FAIR cookbook and RDMkit both provide excellent instructions for uploading your data into databases:
- FAIRcookbook recipe on [Depositing to generic repositories- Zenodo use](https://faircookbook.elixir-europe.org/content/recipes/findability/zenodo-deposition.html)
- FAIRcookbook recipe on [Registering Datasets in Wikidata](https://faircookbook.elixir-europe.org/content/recipes/findability/registeringDatasets.html)
- RDMkit guidelines on [Data publications and depostion](https://rdmkit.elixir-europe.org/data_publication)
- RDMkit guidelines on [Finding and reusing existing data](https://rdmkit.elixir-europe.org/existing_data)
- FAIRcookbook recipe on[Search engine optimization](https://faircookbook.elixir-europe.org/content/recipes/findability/seo.html)
- FAIRsharing offers a nice portal to different [examples of databases](https://fairsharing.org/search?fairsharingRegistry=Database&subjects=life%2520science&page=1)
:::

::: challenge
## Exercise
Using RDMkit explanation on how to [Finding and reusing existing data](https://rdmkit.elixir-europe.org/existing_data), could you find a dataset relevant to your field that you needed for one of your research?
:::
